force-app/main/default/objects/B_n_ficiaire__c/B_n_ficiaire__c.object-meta.xml
<CustomObject>
    <label>Bénéficiaire</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bénéficiaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/B_n_ficiaire__c/fields/Beneficiaire__c.field-meta.xml
<CustomField>
    <fullName>Beneficiaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bénéficiaire du Don</label>
    <referenceTo>Organisateur__c</referenceTo>
    <relationshipLabel>Bénéficiaires</relationshipLabel>
    <relationshipName>B_n_ficiaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Don__c.field-meta.xml
<CustomField>
    <fullName>Don__c</fullName>
    <label>Don</label>
    <referenceTo>Donprotocolairesiege__c</referenceTo>
    <relationshipLabel>Bénéficiaires</relationshipLabel>
    <relationshipName>B_n_ficiaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Part_du_Don__c.field-meta.xml
<CustomField>
    <fullName>Part_du_Don__c</fullName>
    <label>Part du Don</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Type_Don__c.field-meta.xml
<CustomField>
    <fullName>Type_Don__c</fullName>
    <formula>TEXT(Don__r.Type_Don__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Don</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/D_l_gation__c/D_l_gation__c.object-meta.xml
<CustomObject>
    <label>Délégation</label>
    <nameField>
        <label>Nom de Délégation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Délégations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D_l_gation__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <externalId>true</externalId>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/D_l_gation__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DR</label>
    <referenceTo>Direction_R_gionale__c</referenceTo>
    <relationshipLabel>Délégations</relationshipLabel>
    <relationshipName>D_l_gations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direction_R_gionale__c/Direction_R_gionale__c.object-meta.xml
<CustomObject>
    <label>Direction Régionale</label>
    <nameField>
        <label>Nom de Direction Régionale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Directions Régionales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direction_R_gionale__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/Donprotocolairesiege__c.object-meta.xml
<CustomObject>
    <label>Don</label>
    <nameField>
        <displayFormat>Don{0000}</displayFormat>
        <label>Numéro Don</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Civilit__c.field-meta.xml
<CustomField>
    <fullName>Civilit__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madame</fullName>
            </value>
            <value>
                <fullName>Monsieur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/D_cisiondirection__c.field-meta.xml
<CustomField>
    <fullName>D_cisiondirection__c</fullName>
    <label>Décision Direction Réseau</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Accord</fullName>
            </value>
            <value>
                <fullName>Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/D_cisionDL__c.field-meta.xml
<CustomField>
    <fullName>D_cisionDL__c</fullName>
    <label>Décision DL/DT</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Accord</fullName>
            </value>
            <value>
                <fullName>Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_concern_e__c.field-meta.xml
<CustomField>
    <fullName>Date_concern_e__c</fullName>
    <label>Événement : 1 Date concernée</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_de_r_glement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_r_glement__c</fullName>
    <label>Date de règlement des droits d&apos;auteur</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DL_DT__c.field-meta.xml
<CustomField>
    <fullName>DL_DT__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DL/DT</label>
    <referenceTo>D_l_gation__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DOSSIER_COMPLET__c.field-meta.xml
<CustomField>
    <fullName>DOSSIER_COMPLET__c</fullName>
    <label>DOSSIER COMPLET</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <formula>DL_DT__r.DR__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Montant_des_droits__c.field-meta.xml
<CustomField>
    <fullName>Montant_des_droits__c</fullName>
    <label>Montant global des droits d&apos;auteur HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom du responsable</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Note_de_D_pense__c.field-meta.xml
<CustomField>
    <fullName>Note_de_D_pense__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Note de Dépense</label>
    <referenceTo>ND__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Organisateur__c.field-meta.xml
<CustomField>
    <fullName>Organisateur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisateur</label>
    <referenceTo>Organisateur__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pi_ces_Jointes__c.field-meta.xml
<CustomField>
    <fullName>Pi_ces_Jointes__c</fullName>
    <label>Pièces Jointes</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Etat des recettes et dépenses</fullName>
            </value>
            <value>
                <fullName>demande autorisation</fullName>
                <label>Demande d’autorisation</label>
            </value>
            <value>
                <fullName>Contrat général de représentation</fullName>
            </value>
            <value>
                <fullName>Bilan détaillé manifestation</fullName>
            </value>
            <value>
                <fullName>Demande écrite de don jointe</fullName>
            </value>
            <value>
                <fullName>Factures de l&apos;année écoulée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pourcentage_proposition__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_proposition__c</fullName>
    <label>Pourcentage du don</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30%</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pr_nom__c.field-meta.xml
<CustomField>
    <fullName>Pr_nom__c</fullName>
    <label>Prénom du responsable</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>PROPOSITION</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
                <default>true</default>
                <label>En attente</label>
            </value>
            <value>
                <fullName>Accord</fullName>
            </value>
            <value>
                <fullName>Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_de_Tarification__c.field-meta.xml
<CustomField>
    <fullName>Type_de_Tarification__c</fullName>
    <label>Type de Tarification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Au Forfait</fullName>
            </value>
            <value>
                <fullName>Au Pourcentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_Don__c.field-meta.xml
<CustomField>
    <fullName>Type_Don__c</fullName>
    <defaultValue>IF(  $RecordType.Name=&apos;Protocolaire&apos;  , &apos;Protocolaire&apos;, &apos;Appréciation du siège&apos;)</defaultValue>
    <label>Type Don</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Protocolaire</fullName>
            </value>
            <value>
                <fullName>Appréciation du siège</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Validation_Charg_Client_le__c.field-meta.xml
<CustomField>
    <fullName>Validation_Charg_Client_le__c</fullName>
    <label>Validation Chargé Clientèle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Attente</fullName>
            </value>
            <value>
                <fullName>Dossier Complet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ND__c/ND__c.object-meta.xml
<CustomObject>
    <label>Note de Dépense</label>
    <nameField>
        <displayFormat>ND{000}</displayFormat>
        <label>Numéro ND</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes de Dépenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ND__c/fields/Count_Don__c.field-meta.xml
<CustomField>
    <fullName>Count_Don__c</fullName>
    <label>NB Dons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Organisateur__c/Organisateur__c.object-meta.xml
<CustomObject>
    <label>Interlocuteur</label>
    <nameField>
        <label>Nom de la société ou association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interlocuteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_NDDonsCount.cls
@isTest
public class Test_NDDonsCount {
    
 @testSetup static void setup() {
    TestHelper.delegationTest();
    TestHelper.organisateur();
  }

   @isTest static void TestinserdontoND () {
       
     
       List <ND__c> lstNDToUpdate = new List <ND__c>();

        Direction_R_gionale__c dr =new Direction_R_gionale__c (Name='testdr',Code_UO__c='10450', Email__c='testmaildr@outlook.com');
       insert dr;
       
      
       
       
        D_l_gation__c  del =new D_l_gation__c ( 		Name='testdl',Code_UO__c='104', Email__c='testmaildl@outlook.com',DR__c=dr.id);
     insert del;
       
       Organisateur__c organisateur = [Select Id from Organisateur__c where Name = 'UNICEF' LIMIT 1];
        Donprotocolairesiege__c don1 = new Donprotocolairesiege__c(Type_Don__c='Appréciation du siège', 
              Organisateur__c=organisateur.Id,
             Type_de_Tarification__c='Au Pourcentage',

               DL_DT__c	=del.id,
              Civilit__c='Madame',
           Montant_des_droits__c=500, 
            Nom__c='xx',Pr_nom__c='yy', 
            Date_concern_e__c=date.newInstance(2017, 5, 1),
           Date_de_r_glement__c=date.newInstance(2017, 3, 1),
         Pourcentage_proposition__c='30',
          Pi_ces_Jointes__c='	Etat des recettes et dépenses;	Contrat général de représentation;	Bilan détaillé manifestation;	Demande écrite de don jointe');
              
     insert don1;    
       
           B_n_ficiaire__c ben =new B_n_ficiaire__c(Beneficiaire__c=organisateur.Id,Part_du_Don__c=100,Don__c=don1.Id);
insert ben;
        
       
       ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sub.id;
        content.origin = 'H';
        insert content;
       
        ContentVersion content2=new ContentVersion(); 
        content2.Title='Header_Picture2'; 
        content2.PathOnClient='/' + content2.Title + '.jpg'; 
        Blob bodyBlob2=Blob.valueOf('Unit Test ContentVersion Body'); 
        content2.VersionData=bodyBlob2; 
        //content.LinkedEntityId=sub.id;
        content2.origin = 'H';
        insert content2;
       
       ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=don1.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        contentlink.ShareType = 'I';
        contentlink.Visibility = 'AllUsers'; 
        
        
        insert contentlink;   
       
        ContentDocumentLink contentlink1=new ContentDocumentLink();
        contentlink1.LinkedEntityId=don1.id;
        contentlink1.contentdocumentid=[select contentdocumentid from contentversion where id =: content2.id].contentdocumentid;
        contentlink1.ShareType = 'I';
        contentlink1.Visibility = 'AllUsers'; 
        
        
        insert contentlink1;    
       
       
       
       
       
          don1.Validation_Charg_Client_le__c='Dossier Complet';
       update don1;
       	don1.D_cisionDL__c='Accord';
       don1.DOSSIER_COMPLET__c='Oui';
      don1.Statut__c='Accord';
       
        don1.D_cisiondirection__c='Accord' ;
        //don1.Note_de_D_pense__c=ND.id;   
       update don1;
        Set <Id> donIds = new Set <Id>();
   donIds.add(don1.Note_de_D_pense__c);
       
      for(ND__c notedepense:[SELECT Id,Name,Count_Don__c,(Select Id from Dons__r) from ND__c where Id IN: donIds]){
    ND__c NDobj = new ND__c ();
    NDobj.Id = notedepense.Id;
    NDobj.Count_Don__c = notedepense.Dons__r.size();
    lstNDToUpdate.add(NDobj);
} 
       
       
       
       
   
       Test.startTest();
       Database.SaveResult[]   result = Database.update(lstNDToUpdate, false);
        Test.stopTest(); 
     
for (Database.saveResult li:  result) {
    if (li.isSuccess()) {

        // Operation was successful, so get the ID of the record that was processed

        System.debug('Successfully inserted don. don ID: ' + li.getId());

    }
    

    else {

        // Operation failed, so get all errors               

        for(Database.Error err : li.getErrors()) {

            System.debug('The following error has occurred.');                   

            System.debug(err.getStatusCode() + ': ' + err.getMessage());

            System.debug('Account fields that affected this error: ' + err.getFields());

        }

    }

}  
      
    
    
}
    
    
}