force-app/main/default/objects/B_n_ficiaire__c/B_n_ficiaire__c.object-meta.xml
<CustomObject>
    <label>Bénéficiaire</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Numéro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bénéficiaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/B_n_ficiaire__c/fields/DL__c.field-meta.xml
<CustomField>
    <fullName>DL__c</fullName>
    <formula>Don__r.DL_DT__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Don__c.field-meta.xml
<CustomField>
    <fullName>Don__c</fullName>
    <label>Don</label>
    <referenceTo>Donprotocolairesiege__c</referenceTo>
    <relationshipLabel>Bénéficiaires</relationshipLabel>
    <relationshipName>B_n_ficiaires</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/getclotureBen__c.field-meta.xml
<CustomField>
    <fullName>getclotureBen__c</fullName>
    <formula>Don__r.getcloture__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clôturé</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/getValidationnddon__c.field-meta.xml
<CustomField>
    <fullName>getValidationnddon__c</fullName>
    <formula>Don__r.Validation_Note_de_D_pense__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>get nd don</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Montant_don_HT__c.field-meta.xml
<CustomField>
    <fullName>Montant_don_HT__c</fullName>
    <formula>Don__r.Montant_du_Don_HT__c  *  Part_du_Don__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant du don</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Montant_Perception_HT__c.field-meta.xml
<CustomField>
    <fullName>Montant_Perception_HT__c</fullName>
    <formula>IF(   ISPICKVAL(Don__r.Type_Don__c, &apos;Protocolaire&apos;)   , Don__r.Montant_global_des_droits_d_auteur_HT__c  , Don__r.Montant_des_droits__c * Part_du_Don__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant Perception HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/MontantPP__c.field-meta.xml
<CustomField>
    <fullName>MontantPP__c</fullName>
    <formula>Montant_Perception_HT__c * Part_du_Don__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MontantPP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Name_b_n_ficiaire__c.field-meta.xml
<CustomField>
    <fullName>Name_b_n_ficiaire__c</fullName>
    <formula>Beneficiaire__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nom du bénéficiaire</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Name_Ben__c.field-meta.xml
<CustomField>
    <fullName>Name_Ben__c</fullName>
    <label>Name Ben</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Part_du_Don__c.field-meta.xml
<CustomField>
    <fullName>Part_du_Don__c</fullName>
    <label>Part du Don</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Statut_Direction_R_seau__c.field-meta.xml
<CustomField>
    <fullName>Statut_Direction_R_seau__c</fullName>
    <formula>Don__r.getdirectionstatus__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Statut  Direction Réseau</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/B_n_ficiaire__c/fields/Type_Don__c.field-meta.xml
<CustomField>
    <fullName>Type_Don__c</fullName>
    <formula>TEXT(Don__r.Type_Don__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type Don</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/Donprotocolairesiege__c.object-meta.xml
<CustomObject>
    <label>Don</label>
    <nameField>
        <displayFormat>Don{0000}</displayFormat>
        <label>Numéro Don</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Adapt_name_resp__c.field-meta.xml
<CustomField>
    <fullName>Adapt_name_resp__c</fullName>
    <formula>IF( AND ( BEGINS( DL_DT__r.Name , &apos;Délégation&apos;),BEGINS( MID(DL_DT__r.Name, 12, 5) ,&apos;A&apos;)) ,&quot;délégué régional d&apos;&quot; &amp; MID(DL_DT__r.Name, 12, 20) ,
IF( AND ( BEGINS( DL_DT__r.Name , &apos;Délégation&apos;),BEGINS( MID(DL_DT__r.Name, 12, 5) ,&apos;O&apos;)) ,&quot;délégué régional d&apos;&quot; &amp; MID(DL_DT__r.Name, 12, 20),

IF( BEGINS( DL_DT__r.Name , &apos;Délégation&apos;),&apos;délégué régional de &apos;&amp; MID(DL_DT__r.Name, 12, 20),



IF( BEGINS( DL_DT__r.Name , &apos;Direction Territoriale Ile&apos;) ,&apos;directeur territorial &apos;&amp; MID(DL_DT__r.Name, 24, 26),




IF( BEGINS( DL_DT__r.Name , &apos;Direction Territoriale Paris&apos;) ,&apos;directeur territorial de Paris&apos;,&apos;&apos;

)






 ))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adapt name resp</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Adapt_nb_seance__c.field-meta.xml
<CustomField>
    <fullName>Adapt_nb_seance__c</fullName>
    <formula>IF(  Nombre_de_s_ances__c &gt;1 ,&apos;des séances que vous avez organisées les &apos; ,&apos;de la séance que vous avez organisée le &apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adapt nb seance</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Adapt_seance__c.field-meta.xml
<CustomField>
    <fullName>Adapt_seance__c</fullName>
    <formula>IF( ISPICKVAL( Nature_de_la_s_ance__c , &apos;Manifestation&apos;)  ,&apos;de la manifestation que vous avez organisée &apos;  , &apos;du &apos;&amp;  LOWER(TEXT(Nature_de_la_s_ance__c) )&amp;&apos; que vous avez organisé &apos; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adapt seance</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <label>Adresse</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Civilit__c.field-meta.xml
<CustomField>
    <fullName>Civilit__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madame</fullName>
            </value>
            <value>
                <fullName>Monsieur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/CP__c.field-meta.xml
<CustomField>
    <fullName>CP__c</fullName>
    <label>CP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/D_cisiondirection__c.field-meta.xml
<CustomField>
    <fullName>D_cisiondirection__c</fullName>
    <label>Décision Direction Réseau</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente</fullName>
            </value>
            <value>
                <fullName>Accord</fullName>
            </value>
            <value>
                <fullName>Refus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_concern_e__c.field-meta.xml
<CustomField>
    <fullName>Date_concern_e__c</fullName>
    <label>Événement : 1 Date concernée</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_Cr_ation_Don__c.field-meta.xml
<CustomField>
    <fullName>Date_Cr_ation_Don__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de Traitement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DL_DT__c.field-meta.xml
<CustomField>
    <fullName>DL_DT__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DL/DT</label>
    <referenceTo>D_l_gation__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Get_type__c.field-meta.xml
<CustomField>
    <fullName>Get_type__c</fullName>
    <formula>TEXT( Type_Don__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Get type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/getcloture__c.field-meta.xml
<CustomField>
    <fullName>getcloture__c</fullName>
    <formula>TEXT(Cl_tur__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>getcloture</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/getdirectionstatus__c.field-meta.xml
<CustomField>
    <fullName>getdirectionstatus__c</fullName>
    <formula>TEXT (D_cisiondirection__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>getdirectionstatus</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Libelle__c.field-meta.xml
<CustomField>
    <fullName>Libelle__c</fullName>
    <formula>Organisateur__r.Libelle_Forme_Juridique__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LibelleFJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Lieu__c.field-meta.xml
<CustomField>
    <fullName>Lieu__c</fullName>
    <label>Lieu</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Montantdudon__c.field-meta.xml
<CustomField>
    <fullName>Montantdudon__c</fullName>
    <formula>IF( ISPICKVAL(Pourcentage_proposition__c, &quot;50&quot;)  , Montant_des_droits__c   *  50  / 100,  Montant_des_droits__c * 30 / 100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant global du don</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Nature_de_la_s_ance__c.field-meta.xml
<CustomField>
    <fullName>Nature_de_la_s_ance__c</fullName>
    <label>Nature de la séance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>concert</fullName>
                <label>Concert et spectacle de variétés/kermesse</label>
            </value>
            <value>
                <fullName>Bal, soirée dansante</fullName>
            </value>
            <value>
                <fullName>Repas en musique</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Manifestation</fullName>
                <label>Manifestation (autre)</label>
            </value>
            <value>
                <fullName>Manifestations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom du responsable</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pr_nom__c.field-meta.xml
<CustomField>
    <fullName>Pr_nom__c</fullName>
    <label>Prénom du responsable</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_Don__c.field-meta.xml
<CustomField>
    <fullName>Type_Don__c</fullName>
    <defaultValue>IF(  $RecordType.Name=&apos;Protocolaire&apos;  , &apos;Protocolaire&apos;, &apos;Appréciation du siège&apos;)</defaultValue>
    <label>Type Don</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Protocolaire</fullName>
            </value>
            <value>
                <fullName>Appréciation du siège</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Validation_Note_de_D_pense__c.field-meta.xml
<CustomField>
    <fullName>Validation_Note_de_D_pense__c</fullName>
    <label>Validation Note de Dépense</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/recordTypes/protocolaire.recordType-meta.xml
<RecordType>
    <fullName>protocolaire</fullName>
    <active>true</active>
    <label>Protocolaire</label>
</RecordType>

force-app/main/default/objects/Organisateur__c/Organisateur__c.object-meta.xml
<CustomObject>
    <label>Interlocuteur</label>
    <nameField>
        <label>Nom de la société ou association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interlocuteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisateur__c/fields/CP__c.field-meta.xml
<CustomField>
    <fullName>CP__c</fullName>
    <label>CP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisateur__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/benificiairePagination.cls
public with sharing class benificiairePagination {

    public benificiairePagination(ApexPages.StandardController controller) {
Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=Lettre Organisateur.pdf'); 

    }


    public benificiairePagination(ApexPages.StandardSetController controller) {

    }
  public Donprotocolairesiege__c currentDon {get;set;}   
public Donprotocolairesiege__c Don{get;set;}   

public String Namedl {get;set;}
public String libelleor {get;set;}


public String Nameor {get;set;}
public String adresse{get;set;}
public string cp {get;set;}
public String ville {get;set;}
public String benificiaire {get;set;}
public String Pays {get;set;}
public String space{get;set;}

public  String decision{get;set;}
public  String civilite{get;set;}

public  String  headerdata{get;set;}
    public string urlvalue{get;set;}
    public string url{get;set;}

    public benificiairePagination () {

    }
         public Decimal Montant { get; private set; }
         public Decimal Montantdroit { get; private set; }

 
 public String currentRecordId {get;set;}

  public String render{get;set;}

  public Decimal getSomme() {
        AggregateResult[] results = [select SUM(Montant_don_HT__c) from   B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord'and Type_Don__c='Appréciation du siège' and getValidationnddon__c !='Oui'];
         for (AggregateResult ar : results )  {

        Montant =(Decimal) ar.get('expr0');

    } 
        return montant ;

    }
    
    
    
     public Decimal getSommedroitsiege() {
        AggregateResult[] results = [select SUM(Montant_Perception_HT__c) from   B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord'and Type_Don__c='Appréciation du siège' and getValidationnddon__c !='Oui'];
         for (AggregateResult ar : results )  {

        Montantdroit =(Decimal) ar.get('expr0');

    } 
        return Montantdroit;

    }
    
    
    
    
    
     public Decimal getSommeprotocolaire() {
        AggregateResult[] results = [select SUM(Montant_don_HT__c) from   B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord' and Type_Don__c='Protocolaire' and getValidationnddon__c !='Oui'];
         for (AggregateResult ar : results )  {

        Montant =(Decimal) ar.get('expr0');

    } 
        return montant ;

    }
    
    public Decimal getSommedroitprotocolaire() {
        AggregateResult[] results = [select SUM(Montant_Perception_HT__c) from   B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord' and Type_Don__c='Protocolaire' and getValidationnddon__c !='Oui'];
         for (AggregateResult ar : results )  {

        Montantdroit =(Decimal) ar.get('expr0');

    } 
        return montantdroit ;

    }
    
    
      public List<B_n_ficiaire__c> getBeniPro() {
     
      currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
     List<B_n_ficiaire__c> ben=[Select    Name_b_n_ficiaire__c,Montant_Perception_HT__c,Montant_don_HT__c ,DL__c, Part_du_Don__c,MontantPP__c   ,  getValidationnddon__c from B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord' and Type_Don__c='Protocolaire' and     getValidationnddon__c !='Oui'];
 
     return ben ;
     }
       
    
      public List<B_n_ficiaire__c> getBenisiege() {
     
      currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
     List<B_n_ficiaire__c> ben=[Select Name_b_n_ficiaire__c,Montant_Perception_HT__c,Part_du_Don__c,MontantPP__c    ,Montant_don_HT__c ,DL__c,  getValidationnddon__c from B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord' and Type_Don__c='Appréciation du siège' and    getValidationnddon__c !='Oui'];
    
     return ben ;
     }
    
    
    
   

     public void NDBeniPro() {
     
      currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
          List<Donprotocolairesiege__c> donvalidedirection=[Select   id,   Name,Validation_Note_de_D_pense__c from Donprotocolairesiege__c where getcloture__c='En attente' and getdirectionstatus__c='Accord' and Get_type__c='Protocolaire' and Validation_Note_de_D_pense__c !='Oui'];
   
             for(Donprotocolairesiege__c obj : donvalidedirection)
        {
            obj.Validation_Note_de_D_pense__c = 'Oui';
             
        }
    if(donvalidedirection.size() > 0)
        {
            update donvalidedirection;//this seems to just update the list. How do I actually update the custom object?
        }
        
     

     }
     

 public void NDBeniSiege() {
     
      currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
          List<Donprotocolairesiege__c> donvalidedirection=[Select   id,   Name,Validation_Note_de_D_pense__c from Donprotocolairesiege__c where getcloture__c='En attente' and getdirectionstatus__c='Accord' and Get_type__c='Appréciation du siège' and Validation_Note_de_D_pense__c !='Oui'];
   
             for(Donprotocolairesiege__c obj : donvalidedirection)
        {
            obj.Validation_Note_de_D_pense__c = 'Oui';
             
        }
    if(donvalidedirection.size() > 0)
        {
            update donvalidedirection;//this seems to just update the list. How do I actually update the custom object?
        }

     }
     
     
      public AggregateResult[]  getBenigrouped() {
     
      currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
     AggregateResult[]  ben=[Select   Name_Ben__c Name ,SUM(Montant_Perception_HT__c) MontantDroits,SUM(Montant_don_HT__c) Montantdon from B_n_ficiaire__c where getclotureBen__c ='En attente' and Statut_Direction_R_seau__c ='Accord' group by    Name_Ben__c];
     return ben ;
     }
     
    
    public PageReference getRedir() {
 if(render==null){
            render='pdf';
    }
        PageReference newPage;

            newPage = Page.NDProtocolaire;
            return newPage.setRedirect(true);
        

    }
    
    
      public PageReference getRedirsiege() {
 if(render==null){
            render='pdf';
    }
        PageReference newPage;

            newPage = Page.NDAppreciationdusiege;
            return newPage.setRedirect(true);
        

    }
    
    
     public String getstatusdirection() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c  projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, getdirectionstatus__c from Donprotocolairesiege__c where id =: currentRecordId   ];
            decision= projSheet.getdirectionstatus__c;
                System.debug('***** ' + decision);

    return decision;
} 
     
    public boolean getRenderedlettre()

{
String d =getstatusdirection();

Boolean render = (d=='Accord' );

 

return render;

}

   
    public boolean getRenderedlettrerefus()

{
String d =getstatusdirection();

Boolean render = (d=='Refus' );

 

return render;

}
   
    
    
    public List<Donprotocolairesiege__c> Records
{

    get
    {
        try
        {
                currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

            Records = new List<Donprotocolairesiege__c>();
            Records = [SELECT id, Name,Libelle__c, Adapt_name_resp__c,Adapt_nb_seance__c   ,Adapt_seance__c,Montantdudon__c,Type_Don__c,Civilit__c,Nom__c,Pr_nom__c,DL_DT__c,Date_Cr_ation_Don__c,D_cisiondirection__c,Nature_de_la_s_ance__c,   Lieu__c,Date_concern_e__c,Adresse__c,CP__c,Ville__c,Montant_du_Don_HT__c FROM Donprotocolairesiege__c where id =: currentRecordId ]; 
      civilite=Records[0].Civilit__c;
        } 
        catch (Exception ex)
        {
              Records = null;
        }
       
        return Records;
    }
    private set;
}








   public String getNamedelegation() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, DL_DT__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsDL= new List<D_l_gation__c >();

   
      RecordsDL=[SELECT id, Name FROM D_l_gation__c where id =: projSheet.DL_DT__c ]; 
        Namedl =RecordsDL[0].Name;
    return Namedl ;
}


 public String getNameOrganisateur() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, Organisateur__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsOrg= new List<Organisateur__c>();

   
      RecordsOrg=[SELECT id, Name FROM Organisateur__c where id =: projSheet.Organisateur__c]; 
        Nameor =RecordsOrg[0].Name;
    return Nameor ;
}

 public String getAdresseOrganisateur() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, Organisateur__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsOrg= new List<Organisateur__c>();

   
      RecordsOrg=[SELECT id, Adresse__c FROM Organisateur__c where id =: projSheet.Organisateur__c]; 
        adresse =RecordsOrg[0].Adresse__c;
    return adresse ;
}

 public string getCPOrganisateur() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, Organisateur__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsOrg= new List<Organisateur__c>();

   
      RecordsOrg=[SELECT id, CP__c FROM Organisateur__c where id =: projSheet.Organisateur__c]; 
        CP=RecordsOrg[0].CP__c ;
    return CP;
}
    







 public String getVilleOrganisateur() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, Organisateur__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsOrg= new List<Organisateur__c>();

   
      RecordsOrg=[SELECT id,    Ville__c FROM Organisateur__c where id =: projSheet.Organisateur__c]; 
        ville=RecordsOrg[0].Ville__c;
    return ville;
}


 /*public String getNameBeni() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name,  B_n_ficiaire__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsBEN= new List<B_n_ficiaire__c>();

   
      RecordsBEN=[SELECT id,    Name FROM B_n_ficiaire__c where id =: projSheet.B_n_ficiaire__c ]; 
        benificiaire =RecordsBEN[0].Name;
    return benificiaire ;
}*/
  public String getNameBeni() {
  List<String> lstNames = new List<String>();

             currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

List<B_n_ficiaire__c > conresults = [Select  Name_b_n_ficiaire__c from B_n_ficiaire__c  where Don__c=: currentRecordId ];

for(B_n_ficiaire__c  ac: [Select  Name_b_n_ficiaire__c from B_n_ficiaire__c  where Don__c=: currentRecordId]){
    lstNames.add(ac.Name_b_n_ficiaire__c );
}

String names = string.join(lstNames,' et de ');

return names ;
}




 public String getspaceOrganisateur() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, Organisateur__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsOrg= new List<Organisateur__c>();

   
      RecordsOrg=[SELECT id,    Ville__c FROM Organisateur__c where id =: projSheet.Organisateur__c]; 
        space=' ';
    return space;
}







public List<D_l_gation__c> RecordsDL {

    get
    {
        try
        {
               currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, DL_DT__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsDL= new List<D_l_gation__c >();

   
      RecordsDL=[SELECT id, Name FROM D_l_gation__c where id =: projSheet.DL_DT__c ]; 

        } 
        catch (Exception ex)
        {
              RecordsDL = null;
        }
        return RecordsDL ;
    }
    private set;
}


public List<Organisateur__c> RecordsOrg {

    get
    {
        try
        {
               currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');

   

             Donprotocolairesiege__c projSheet = new Donprotocolairesiege__c ();
              projSheet  =[Select id, Name, Organisateur__c from Donprotocolairesiege__c where id =: currentRecordId ];
               RecordsOrg= new List<Organisateur__c>();

   
      RecordsOrg=[SELECT id, Name,Adresse__c,CP__c,Ville__c,Pays__c FROM Organisateur__c where id =: projSheet.Organisateur__c  ]; 

        } 
        catch (Exception ex)
        {
              RecordsOrg = null;
        }
        return RecordsOrg ;
    }
    private set;
}



private Map<Integer, String> frenchDates = new Map<Integer, String>();


public String formattedDateNow {
    get {
    frenchDates.put(1, 'Janvier');
frenchDates.put(2, 'Février');
frenchDates.put(3, 'Mars');
frenchDates.put(4, 'Avril');
frenchDates.put(5, 'Mai');
frenchDates.put(6, 'Juin');
frenchDates.put(7, 'Juillet');
frenchDates.put(8, 'Aout');
frenchDates.put(9, 'Septembre');
frenchDates.put(10, 'Octobre');
frenchDates.put(11, 'Novembre');
frenchDates.put(12, 'Décembre'); 
        Datetime dateNow = Datetime.now();
        return 'Le '+ String.valueOf(dateNow.day()) +' '+ frenchDates.get(dateNow.month()) +' '+ String.valueOf(dateNow.year());
    }
    set;
}


public String formattedDateeven1Protocolaire {
    get {
    frenchDates.put(1, 'Janvier');
frenchDates.put(2, 'Février');
frenchDates.put(3, 'Mars');
frenchDates.put(4, 'Avril');
frenchDates.put(5, 'Mai');
frenchDates.put(6, 'Juin');
frenchDates.put(7, 'Juillet');
frenchDates.put(8, 'Aout');
frenchDates.put(9, 'Septembre');
frenchDates.put(10, 'Octobre');
frenchDates.put(11, 'Novembre');
frenchDates.put(12, 'Décembre');
    
            currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
 
             List<Donprotocolairesiege__c> projSheet = new List<Donprotocolairesiege__c>();
              projSheet  =[Select id, Date_concern_e__c,v_nement_2_Date_concern_e__c,Nombre_de_s_ances__c from Donprotocolairesiege__c where id =: currentRecordId ];

   
        Decimal nbS=projSheet[0].Nombre_de_s_ances__c ;
        
    
    
        Datetime d1= projSheet[0].Date_concern_e__c ;
        Datetime d2= projSheet[0].v_nement_2_Date_concern_e__c ;
        
        if(nbS == 1 )

        return String.valueOf(d1.day()) +' '+ frenchDates.get(d1.month()) +' '+ String.valueOf(d1.year());
        else 
        return String.valueOf(d1.day()) +' '+ frenchDates.get(d1.month()) +' '+ String.valueOf(d1.year()) + ' et '+String.valueOf(d2.day()) +' '+ frenchDates.get(d2.month()) +' '+ String.valueOf(d2.year());

    }
    set;
}



public String formattedDateeven1Siege {
    get {
    frenchDates.put(1, 'Janvier');
frenchDates.put(2, 'Février');
frenchDates.put(3, 'Mars');
frenchDates.put(4, 'Avril');
frenchDates.put(5, 'Mai');
frenchDates.put(6, 'Juin');
frenchDates.put(7, 'Juillet');
frenchDates.put(8, 'Aout');
frenchDates.put(9, 'Septembre');
frenchDates.put(10, 'Octobre');
frenchDates.put(11, 'Novembre');
frenchDates.put(12, 'Décembre');
    
            currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
 
             List<Donprotocolairesiege__c> projSheet = new List<Donprotocolairesiege__c>();
              projSheet  =[Select id, Date_concern_e__c from Donprotocolairesiege__c where id =: currentRecordId ];

   
        
    
    
        Datetime d1= projSheet[0].Date_concern_e__c ;
        return ' '+ String.valueOf(d1.day()) +' '+ frenchDates.get(d1.month()) +' '+ String.valueOf(d1.year());
    }
    set;
}



    
    }