force-app/main/default/objects/D_l_gation__c/D_l_gation__c.object-meta.xml
<CustomObject>
    <label>Délégation</label>
    <nameField>
        <label>Nom de Délégation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Délégations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D_l_gation__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <externalId>true</externalId>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/D_l_gation__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DR</label>
    <referenceTo>Direction_R_gionale__c</referenceTo>
    <relationshipLabel>Délégations</relationshipLabel>
    <relationshipName>D_l_gations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direction_R_gionale__c/Direction_R_gionale__c.object-meta.xml
<CustomObject>
    <label>Direction Régionale</label>
    <nameField>
        <label>Nom de Direction Régionale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Directions Régionales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direction_R_gionale__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/Donprotocolairesiege__c.object-meta.xml
<CustomObject>
    <label>Don</label>
    <nameField>
        <displayFormat>Don{0000}</displayFormat>
        <label>Numéro Don</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <label>Adresse</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Civilit__c.field-meta.xml
<CustomField>
    <fullName>Civilit__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madame</fullName>
            </value>
            <value>
                <fullName>Monsieur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_concern_e__c.field-meta.xml
<CustomField>
    <fullName>Date_concern_e__c</fullName>
    <label>Événement : 1 Date concernée</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_de_r_glement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_r_glement__c</fullName>
    <label>Date de règlement des droits d&apos;auteur</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DL_DT__c.field-meta.xml
<CustomField>
    <fullName>DL_DT__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DL/DT</label>
    <referenceTo>D_l_gation__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <formula>DL_DT__r.DR__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Montant_des_droits__c.field-meta.xml
<CustomField>
    <fullName>Montant_des_droits__c</fullName>
    <label>Montant global des droits d&apos;auteur HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom du responsable</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Organisateur__c.field-meta.xml
<CustomField>
    <fullName>Organisateur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisateur</label>
    <referenceTo>Organisateur__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pi_ces_Jointes__c.field-meta.xml
<CustomField>
    <fullName>Pi_ces_Jointes__c</fullName>
    <label>Pièces Jointes</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Etat des recettes et dépenses</fullName>
            </value>
            <value>
                <fullName>demande autorisation</fullName>
                <label>Demande d’autorisation</label>
            </value>
            <value>
                <fullName>Contrat général de représentation</fullName>
            </value>
            <value>
                <fullName>Bilan détaillé manifestation</fullName>
            </value>
            <value>
                <fullName>Demande écrite de don jointe</fullName>
            </value>
            <value>
                <fullName>Factures de l&apos;année écoulée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pourcentage_proposition__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_proposition__c</fullName>
    <label>Pourcentage du don</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30%</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pr_nom__c.field-meta.xml
<CustomField>
    <fullName>Pr_nom__c</fullName>
    <label>Prénom du responsable</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_de_Tarification__c.field-meta.xml
<CustomField>
    <fullName>Type_de_Tarification__c</fullName>
    <label>Type de Tarification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Au Forfait</fullName>
            </value>
            <value>
                <fullName>Au Pourcentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_Don__c.field-meta.xml
<CustomField>
    <fullName>Type_Don__c</fullName>
    <defaultValue>IF(  $RecordType.Name=&apos;Protocolaire&apos;  , &apos;Protocolaire&apos;, &apos;Appréciation du siège&apos;)</defaultValue>
    <label>Type Don</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Protocolaire</fullName>
            </value>
            <value>
                <fullName>Appréciation du siège</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organisateur__c/Organisateur__c.object-meta.xml
<CustomObject>
    <label>Interlocuteur</label>
    <nameField>
        <label>Nom de la société ou association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interlocuteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_donListExt.cls
@isTest
public class Test_donListExt {

  @testSetup static void setup() {
    TestHelper.delegationTest();
    TestHelper.organisateur();
  }

    public static testMethod void testMyController() {
        
        // create a list
        List <Donprotocolairesiege__c> List_Dons = new List<Donprotocolairesiege__c>();
    Direction_R_gionale__c dr =new Direction_R_gionale__c (Name='testdr',Code_UO__c='10450', Email__c='testmaildr@outlook.com');
       insert dr;
        D_l_gation__c  del =new D_l_gation__c ( 		Name='testdl',Code_UO__c='104', Email__c='testmaildl@outlook.com',DR__c=dr.id);
     insert del;
       
       Organisateur__c organisateur = [Select Id from Organisateur__c where Name = 'UNICEF' LIMIT 1];
        Donprotocolairesiege__c don1 = new Donprotocolairesiege__c(Type_Don__c='Appréciation du siège', 
              Organisateur__c=organisateur.Id,
                                                                                Type_de_Tarification__c='Au Pourcentage',

               DL_DT__c	=del.id,
              Civilit__c='Madame',
           Montant_des_droits__c=500, 
            Nom__c='xx',Pr_nom__c='yy', 
            Date_concern_e__c=date.newInstance(2017, 5, 1),
           Date_de_r_glement__c=date.newInstance(2017, 3, 1),
         Pourcentage_proposition__c='30',
          Pi_ces_Jointes__c='	Etat des recettes et dépenses;	Contrat général de représentation;	Bilan détaillé manifestation;	Demande écrite de don jointe');
        don1.Adresse__c='First Test Don' ;
        List_Dons.add(don1);
        
        Donprotocolairesiege__c don2 = new Donprotocolairesiege__c(Type_Don__c='Appréciation du siège', 
              Organisateur__c=organisateur.Id,
                                                                                Type_de_Tarification__c='Au Pourcentage',

               DL_DT__c	=del.id,
              Civilit__c='Madame',
           Montant_des_droits__c=500, 
            Nom__c='xx',Pr_nom__c='yy', 
            Date_concern_e__c=date.newInstance(2017, 5, 1),
           Date_de_r_glement__c=date.newInstance(2017, 3, 1),
         Pourcentage_proposition__c='30',
          Pi_ces_Jointes__c='	Etat des recettes et dépenses;	Contrat général de représentation;	Bilan détaillé manifestation;	Demande écrite de don jointe');
        don2.Adresse__c='Second Test Don' ;
        List_Dons.add(don2);
        
        insert List_Dons;
        
        Test.startTest();
        Test.setCurrentPage(Page.GenerateDocumentsCA);
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(List_Dons);
        stdSetController.setSelected(List_Dons);
        
        donListExt ext = new donListExt(stdSetController);
        ext.init();
        
        Test.stopTest();
    }
}