force-app/main/default/objects/D_l_gation__c/D_l_gation__c.object-meta.xml
<CustomObject>
    <label>Délégation</label>
    <nameField>
        <label>Nom de Délégation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Délégations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D_l_gation__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <externalId>true</externalId>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/D_l_gation__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DR</label>
    <referenceTo>Direction_R_gionale__c</referenceTo>
    <relationshipLabel>Délégations</relationshipLabel>
    <relationshipName>D_l_gations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Direction_R_gionale__c/Direction_R_gionale__c.object-meta.xml
<CustomObject>
    <label>Direction Régionale</label>
    <nameField>
        <label>Nom de Direction Régionale</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Directions Régionales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Direction_R_gionale__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisateur__c/Organisateur__c.object-meta.xml
<CustomObject>
    <label>Interlocuteur</label>
    <nameField>
        <label>Nom de la société ou association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interlocuteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisateur__c/fields/CP__c.field-meta.xml
<CustomField>
    <fullName>CP__c</fullName>
    <label>CP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisateur__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisateur__c/fields/refclient__c.field-meta.xml
<CustomField>
    <fullName>refclient__c</fullName>
    <externalId>true</externalId>
    <label>Référence Client</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisateur__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestHelper.cls
@isTest
public class TestHelper {

@isTest public static void delegationTest() {
	Direction_R_gionale__c dr = new Direction_R_gionale__c();
	dr.Code_UO__c = 'C0407';
	dr.Email__c = 'dr.nidf@sacem.fr';
	dr.Name = 'DR ILE de France';
	insert dr;

	D_l_gation__c delegation = new D_l_gation__c();
	delegation.Code_UO__c = 'C040701';
	delegation.DR__c = dr.id;
	delegation.Email__c = 'dl.paris@sacem.fr';
	delegation.Name = 'Direction Territoriale Paris';
	insert delegation;
}

@isTest public static void organisateur() {
	Organisateur__c org =new Organisateur__c(   Name='UNICEF', Adresse__c='1 terrasse Bellini',CP__c='92800', Pays__c='France',Ville__c='Puteaux', refclient__c='12345678');
	insert org;
}

}