force-app/main/default/objects/D_l_gation__c/D_l_gation__c.object-meta.xml
<CustomObject>
    <label>Délégation</label>
    <nameField>
        <label>Nom de Délégation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Délégations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/D_l_gation__c/fields/Code_UO__c.field-meta.xml
<CustomField>
    <fullName>Code_UO__c</fullName>
    <externalId>true</externalId>
    <label>Code UO</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/Donprotocolairesiege__c.object-meta.xml
<CustomObject>
    <label>Don</label>
    <nameField>
        <displayFormat>Don{0000}</displayFormat>
        <label>Numéro Don</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Civilit__c.field-meta.xml
<CustomField>
    <fullName>Civilit__c</fullName>
    <label>Civilité</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Madame</fullName>
            </value>
            <value>
                <fullName>Monsieur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_concern_e__c.field-meta.xml
<CustomField>
    <fullName>Date_concern_e__c</fullName>
    <label>Événement : 1 Date concernée</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Date_de_r_glement__c.field-meta.xml
<CustomField>
    <fullName>Date_de_r_glement__c</fullName>
    <label>Date de règlement des droits d&apos;auteur</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/DL_DT__c.field-meta.xml
<CustomField>
    <fullName>DL_DT__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DL/DT</label>
    <referenceTo>D_l_gation__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Montant_des_droits__c.field-meta.xml
<CustomField>
    <fullName>Montant_des_droits__c</fullName>
    <label>Montant global des droits d&apos;auteur HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Nature_de_la_s_ance__c.field-meta.xml
<CustomField>
    <fullName>Nature_de_la_s_ance__c</fullName>
    <label>Nature de la séance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>concert</fullName>
                <label>Concert et spectacle de variétés/kermesse</label>
            </value>
            <value>
                <fullName>Bal, soirée dansante</fullName>
            </value>
            <value>
                <fullName>Repas en musique</fullName>
            </value>
            <value>
                <fullName>Festival</fullName>
            </value>
            <value>
                <fullName>Manifestation</fullName>
                <label>Manifestation (autre)</label>
            </value>
            <value>
                <fullName>Manifestations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Nom__c.field-meta.xml
<CustomField>
    <fullName>Nom__c</fullName>
    <label>Nom du responsable</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Organisateur__c.field-meta.xml
<CustomField>
    <fullName>Organisateur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisateur</label>
    <referenceTo>Organisateur__c</referenceTo>
    <relationshipLabel>Dons</relationshipLabel>
    <relationshipName>Dons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pi_ces_Jointes__c.field-meta.xml
<CustomField>
    <fullName>Pi_ces_Jointes__c</fullName>
    <label>Pièces Jointes</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Etat des recettes et dépenses</fullName>
            </value>
            <value>
                <fullName>demande autorisation</fullName>
                <label>Demande d’autorisation</label>
            </value>
            <value>
                <fullName>Contrat général de représentation</fullName>
            </value>
            <value>
                <fullName>Bilan détaillé manifestation</fullName>
            </value>
            <value>
                <fullName>Demande écrite de don jointe</fullName>
            </value>
            <value>
                <fullName>Factures de l&apos;année écoulée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pourcentage_proposition__c.field-meta.xml
<CustomField>
    <fullName>Pourcentage_proposition__c</fullName>
    <label>Pourcentage du don</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
                <label>30%</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>50%</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Pr_nom__c.field-meta.xml
<CustomField>
    <fullName>Pr_nom__c</fullName>
    <label>Prénom du responsable</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_de_Tarification__c.field-meta.xml
<CustomField>
    <fullName>Type_de_Tarification__c</fullName>
    <label>Type de Tarification</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Au Forfait</fullName>
            </value>
            <value>
                <fullName>Au Pourcentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Type_Don__c.field-meta.xml
<CustomField>
    <fullName>Type_Don__c</fullName>
    <defaultValue>IF(  $RecordType.Name=&apos;Protocolaire&apos;  , &apos;Protocolaire&apos;, &apos;Appréciation du siège&apos;)</defaultValue>
    <label>Type Don</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Protocolaire</fullName>
            </value>
            <value>
                <fullName>Appréciation du siège</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Donprotocolairesiege__c/fields/Validation_Charg_Client_le__c.field-meta.xml
<CustomField>
    <fullName>Validation_Charg_Client_le__c</fullName>
    <label>Validation Chargé Clientèle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Attente</fullName>
            </value>
            <value>
                <fullName>Dossier Complet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Organisateur__c/Organisateur__c.object-meta.xml
<CustomObject>
    <label>Interlocuteur</label>
    <nameField>
        <label>Nom de la société ou association</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interlocuteurs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestValidation_piecejointe.cls
@isTest

public class TestValidation_piecejointe {
    
@testSetup static void setup() {
    TestHelper.delegationTest();
    TestHelper.organisateur();
}

@isTest public static void testDonPJ  () {
     integer  nb =3;
     D_l_gation__c dl = [Select Id from D_l_gation__c where Code_UO__c = 'C040701' LIMIT 1];
     Organisateur__c organisateur = [Select Id from Organisateur__c where Name = 'UNICEF' LIMIT 1];
          
    Donprotocolairesiege__c don = new Donprotocolairesiege__c( Type_Don__c='Appréciation du siège', 	DL_DT__c=dl.id,
              Organisateur__c=organisateur.id,
               Type_de_Tarification__c='Au Pourcentage',
              Civilit__c='Madame',
           Montant_des_droits__c=500, 
            Nom__c='xx',Pr_nom__c='yy', 
            Date_concern_e__c=date.newInstance(2017, 5, 1),
           Date_de_r_glement__c=date.newInstance(2017, 3, 1),
           Nature_de_la_s_ance__c=''  ,
         Pourcentage_proposition__c='30',
          Pi_ces_Jointes__c='	Etat des recettes et dépenses;	Contrat général de représentation;	Bilan détaillé manifestation;	Demande écrite de don jointe');
    insert don ;
    
              
        
   don.Validation_Charg_Client_le__c='Dossier Complet';
    
    

    }    

}